/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffe167",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#444938",
        primary: "#4a6500",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#384e00",
        "secondary-container": "#c3ef56",
        "secondary-fixed": "#c6f259",
        "on-tertiary-fixed-variant": "#544600",
        "on-primary-container": "#fbffe6",
        "tertiary-container": "#c7aa16",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#221b00",
        "on-error": "#ffffff",
        outline: "#757967",
        "primary-fixed": "#c9f074",
        "on-secondary-fixed-variant": "#394d00",
        secondary: "#4d6700",
        "surface-tint": "#4c6700",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "primary-fixed-dim": "#aed45c",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed": "#151f00",
        "outline-variant": "#c5c9b4",
        "on-tertiary-container": "#4c3f00",
        background: "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#abd53f",
        "inverse-primary": "#aed45c",
        "primary-container": "#5f7f08",
        "on-secondary-container": "#516b00",
        "tertiary-fixed-dim": "#e4c536",
        "surface-container": "#e5eeff",
        "surface-dim": "#cbdbf5",
        tertiary: "#6f5d00",
        "on-primary-fixed": "#141f00",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        surface: "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "custom-income": "#A1CB35",
        "custom-expense": "#FF9D4D",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "touch-target-min": "48px",
        "stack-lg": "24px",
        "stack-md": "16px",
        gutter: "16px",
        "container-padding": "20px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "display-numeric": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "display-numeric": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg-mobile": [
          "22px",
          { lineHeight: "28px", fontWeight: "700" },
        ],
        "headline-md": [
          "20px",
          { lineHeight: "28px", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}

